# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d10ecdfa563a30993a90b7044a32835ee784aa87d16ee87843c81d7ce7cb114a82fff0788d8de2817e748a89169bc87d90d1deb779407daab90b3f69b7ba3021

test:
  secret_key_base: cfb55b7e6115ba4b11108f1ec62d3f6bae93b07c40a7dd447caf3e0b04df13a99ed47e2bc5da6d0bf16ef4490b4a57eae9fe3f3d632d4cce33d876ca01d24c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
